- hosts: localhost
  become: true

  include_vars:
    - config.yml

  pre_tasks:
    - include_tasks:
      - "tasks/{{ansible_facts['os_family']|lower}}/pre.yml"
      - "tasks/pre.yml"

  tasks:
    - include_tasks: tasks/auto_update.yml
    - include_tasks:
      - "tasks/pre-{{ansible_facts['os_family']|lower}}"
    - include_tasks: tasks/packages.yml
