- hosts: localhost

  vars_files:
    - config.yml

  pre_tasks:
    - include_vars: vars/common.yml
    - include_vars: "{{item}}"
      with_first_found:
        - files:
            - "vars/{{ansible_facts['os_family']|lower}}.yml"
          skip: true
    - include_tasks: "tasks/pre.yml"
    - include_tasks: "{{prerequisites_file}}"
      with_first_found:
        - files:
            - "tasks/{{ansible_facts['os_family']|lower}}/pre.yml"
          skip: true
      loop_control:
        loop_var: prerequisites_file

  tasks:
    - include_tasks: tasks/packages.yml
      tags: [packages,homebrew,mas,cask]
    - include_tasks: tasks/git.yml
      tags: [git]
    - include_tasks: tasks/dotfiles.yml
      tags: [dotfiles]
    - include_tasks: tasks/shell.yml
      tags: [shell]
    - include_tasks: tasks/vscode.yml
      tags: [vscode]
    - include_tasks: tasks/post.yml
      tags: [post]
    - include_tasks: "{{post_file}}"
      with_first_found:
        - files:
            - "tasks/{{ansible_facts['os_family']|lower}}/post.yml"
          skip: true
      loop_control:
        loop_var: post_file
      tags: [post]
