- git_config:
    name: user.name
    scope: global
    value: James Roeder
- git_config:
    name: user.email
    scope: global
    value: jmaroeder@gmail.com
- git_config:
    name: core.excludesfile
    scope: global
    value: "{{ansible_user_dir}}/.gitignore"
- block:
    - git_config:
        name: credential.helper
        scope: global
        value: osxkeychain
    - name: Store github access token in keychain
      command: "security add-internet-password -a '{{github_user}}' -s 'github.com' -w '{{github_access_token}}' -r 'htps' -U"
  when: ansible_os_family == "Darwin"
