- name: Install fisher
  block:
    - file:
        path: "{{ansible_user_dir}}/.config/fish/functions"
        state: directory

    - get_url:
        url: https://git.io/fisher
        dest: "{{ansible_user_dir}}/.config/fish/functions/fisher.fish"

- name: Load fishfile
  shell: fish -c fisher
  when: login_shell == 'fish'
