- name: VS Code Extensions
  include_role:
    name: gantsign.visual-studio-code-extensions
    users:
    - username: "{{primary_user}}"
      visual_studio_code_extensions:
        - mauve.terraform
        - mikestead.dotenv
        - ms-azuretools.vscode-docker
        - redhat.vscode-yaml
        - skyapps.fish-vscode
        - vscoss.vscode-ansible
        - wholroyd.jinja
