- name: Add homebrew shells to /etc/shells
  become: true
  block:
  - name: Check if homebrew bash is installed
    stat:
      path: /usr/local/bin/bash
    register: brew_bash
  - name: Add homebrew bash to /etc/shells
    lineinfile:
      dest: /etc/shells
      line: "/usr/local/bin/bash"
      state: present
    when: brew_bash.stat.exists
  - name: Check if homebrew zsh is installed
    stat:
      path: /usr/local/bin/zsh
    register: brew_zsh
  - name: Add homebrew zsh to /etc/shells
    lineinfile:
      dest: /etc/shells
      line: "/usr/local/bin/zsh"
      state: present
    when: brew_zsh.stat.exists
  - name: Check if homebrew fish is installed
    stat:
      path: /usr/local/bin/fish
    register: brew_fish
  - name: Add homebrew fish to /etc/shells
    lineinfile:
      dest: /etc/shells
      line: "/usr/local/bin/fish"
      state: present
    when: brew_fish.stat.exists

- name: Check if preferred login_shell is installed
  stat:
    path: "{{login_shell}}"
  register: login_shell_installed

- name: Set default shell
  become: true
  user:
    name: "{{ansible_user_id}}"
    shell: "{{login_shell}}"
  when: login_shell_installed.stat.exists
